name: Wallet
on: [push]
jobs:
  tests:
    runs-on: ubuntu-22.04
    container: shrnkm/computational-workflows-homework

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Run tests
        run: |
          python3 -m pytest
